channels:
- defaults
dependencies:
- python=3.6.2
- pip
- pip:
  - mlflow
  - cloudpickle==1.3.0
  - https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  - torchvision==0.5.0
  - Pillow==6.0.0
name: mlflow-env
