# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  - --index-url https://azuremlsdktestpypi.azureedge.net/AzureML-Contrib-Explain-Model-Gated/3010237
  - --extra-index-url https://pypi.python.org/simple
  - sklearn_pandas
  - azureml-defaults<0.1.50
  - azureml-contrib-explain-model<0.1.50
  - azureml-core<0.1.50
  - azureml-telemetry<0.1.50
  - azureml-explain-model<0.1.50
- scikit-learn
